version: 0.2

phases:
  install:
    commands:
      - echo "installing mysql client"
      - yum install -y mysql
      - echo "mysql client instalation done "
      - echo "connecting to the database"
      - mysql --host=ntier.cvvkrojoestg.us-east-1.rds.amazonaws.com --port=3306 --user=admin --password=password ntier -e "SHOW TABLES; CREATE TABLE users6 (name VARCHAR(20), email VARCHAR(20)); SHOW TABLES;"
      - mysql --host=ntier.cvvkrojoestg.us-east-1.rds.amazonaws.com --port=3306 --user=admin --password=password ntier -e "INSERT INTO 'users6' ('name', 'email') VALUES ('user1', 'user1-gmail.com'); SELECT * FROM users;"
     
