version: 0.2

phases:
  install:
    commands:
      - echo "installing mysql client"
      - yum install -y mysql
      - echo "mysql client instalation done "
      - echo "connecting to the database"
      - mysql --host=ntier.cvvkrojoestg.us-east-1.rds.amazonaws.com --port=3306 --user=admin --password=password ntier -e "SHOW TABLES; CREATE TABLE users (name VARCHAR(20), email VARCHAR(20)); INSERT INTO users(name, email) VALUES(user1, user1@gmail.com); SELECT * FROM users"
      #- echo "creating the name table"
      #- mysql show tables ntier;
      #- mysql create table users (name VARCHAR(20), email VARCHAR(20));
      #- mysql show tables;
